### Trabalho 1 - MIneração de dados
O objetivo deste exercício é explorar, tratar e visualizar dados públicos do Brasil disponibilizados pelo IBGE, aplicando técnicas de mineração de dados e construção de gráficos estatísticos.

Os datasets escolhidos foram: 
- PIB dos Municípios – dados econômicos por cidade.
- SIDRA (Sistema IBGE de Recuperação Automática)

In [474]:
import pandas as pd
import numpy as np
from pathlib import Path

caminho1 = Path("datas/PIBMunicipios.csv")
caminho2 = Path("datas/tabela_ensino.xlsx")

df_pib = pd.read_csv(caminho1, sep=';', skiprows=1, nrows=1, encoding='utf-8')
df_educacao = pd.read_excel(caminho2, skiprows=4)

display(df_pib)
display(df_educacao)

,Acre,Alagoas,Amapá,Amazonas,Bahia,Ceará,Distrito Federal,Espírito Santo,Goiás,Maranhão,...,Piauí,Rio Grande do Norte,Rio Grande do Sul,Rio de Janeiro,Rondônia,Roraima,Santa Catarina,Sergipe,São Paulo,Tocantins
0,26291321,89688932,28020120,161794976,430987853,232239257,365669108,209829732,336746975,149227195,...,80916856,101740275,650107022,1172871443,76456179,25124805,513392973,60816662,3444814033,64317699

,Unnamed: 0,Ensino superior completo ou equivalente,Ensino superior completo ou equivalente.1,Ensino superior completo ou equivalente.2,Ensino superior completo ou equivalente.3
0,Rondônia,11.1,10.9,11.0,11.0
1,Acre,11.2,10.8,10.9,11.0
2,Amazonas,10.8,10.9,11.1,11.8
3,Roraima,13.9,13.0,13.0,13.4
4,Pará,9.1,8.9,9.2,9.3
5,Amapá,14.8,15.4,15.8,16.1
6,Tocantins,13.4,13.3,13.7,13.1
7,Maranhão,8.0,8.0,8.0,8.0
8,Piauí,11.8,11.0,11.0,10.5
9,Ceará,9.5,9.4,9.4,9.9
10,Rio Grande do Norte,10.8,10.8,11.3,12.1
11,Paraíba,9.8,9.6,9.9,10.4
12,Pernambuco,10.4,10.3,10.3,10.2
13,Alagoas,8.8,8.8,9.4,9.5
14,Sergipe,9.8,10.2,10.3,10.2
15,Bahia,8.3,8.3,8.7,8.8
16,Minas Gerais,13.0,13.1,13.3,13.5
17,Espírito Santo,14.3,14.3,14.1,14.5
18,Rio de Janeiro,18.7,18.8,18.9,18.8
19,São Paulo,18.6,18.8,19.1,19.3
20,Paraná,15.1,15.1,15.4,15.7
21,Santa Catarina,15.0,15.6,16.1,16.1
22,Rio Grande do Sul,14.6,14.2,14.6,15.0
23,Mato Grosso do Sul,15.9,16.6,16.2,16.5
24,Mato Grosso,13.0,13.3,13.6,13.9
25,Goiás,13.8,14.5,14.4,14.7
26,Distrito Federal,28.1,28.2,28.1,28.9
27,Fonte: IBGE - Pesquisa Nacional por Amostra de...,NaN,NaN,NaN,NaN

In [475]:
print("Quantidade de linhas e colunas:", df_pib.shape)

df_pib.info()

print('Quantidade de duplicatas:', df_pib.duplicated().sum())

Quantidade de linhas e colunas: (1, 27)
<class 'pandas.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 27 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Acre                 1 non-null      int64
 1   Alagoas              1 non-null      int64
 2   Amapá                1 non-null      int64
 3   Amazonas             1 non-null      int64
 4   Bahia                1 non-null      int64
 5   Ceará                1 non-null      int64
 6   Distrito Federal     1 non-null      int64
 7   Espírito Santo       1 non-null      int64
 8   Goiás                1 non-null      int64
 9   Maranhão             1 non-null      int64
 10  Mato Grosso          1 non-null      int64
 11  Mato Grosso do Sul   1 non-null      int64
 12  Minas Gerais         1 non-null      int64
 13  Paraná               1 non-null      int64
 14  Paraíba              1 non-null      int64
 15  Pará                 1 non-null      int64
 16  Pernambuco           1 non-null      int64
 17  Piauí                1 non-null      int64
 18  Rio Grande do Norte  1 non-null      int64
 19  Rio Grande do Sul    1 non-null      int64
 20  Rio de Janeiro       1 non-null      int64
 21  Rondônia             1 non-null      int64
 22  Roraima              1 non-null      int64
 23  Santa Catarina       1 non-null      int64
 24  Sergipe              1 non-null      int64
 25  São Paulo            1 non-null      int64
 26  Tocantins            1 non-null      int64
dtypes: int64(27)
memory usage: 348.0 bytes
Quantidade de duplicatas: 0

In [476]:
print("Quantidade de linhas e colunas:", df_educacao.shape)

df_educacao.info()

print('Quantidade de duplicatas:', df_educacao.duplicated().sum())

Quantidade de linhas e colunas: (28, 5)
<class 'pandas.DataFrame'>
RangeIndex: 28 entries, 0 to 27
Data columns (total 5 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   Unnamed: 0                                 28 non-null     str
 1   Ensino superior completo ou equivalente    27 non-null     float64
 2   Ensino superior completo ou equivalente.1  27 non-null     float64
 3   Ensino superior completo ou equivalente.2  27 non-null     float64
 4   Ensino superior completo ou equivalente.3  27 non-null     float64
dtypes: float64(4), str(1)
memory usage: 1.2 KB
Quantidade de duplicatas: 0

##### Tratamento dos dados

In [477]:
def formato_brl(valor):
    return f'R$ {valor:,.2f}'

In [ ]:
df_pib_copy = df_pib.copy()

df_pib_copy = df_pib_copy.T

df_pib_copy.columns = ['pib']

df_pib_copy['pib_bilhoes'] = df_pib_copy['pib'] / 1_000_000

display(df_pib_copy.style.format({'pib': formato_brl}))

<class 'pandas.DataFrame'>
Index: 27 entries, Acre to Tocantins
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   pib          27 non-null     int64
 1   pib_bilhoes  27 non-null     float64
dtypes: float64(1), int64(1)
memory usage: 1.7+ KB

In [ ]:
df_educacao_copy = df_educacao.set_index(df_educacao.columns[0])

df_educacao_copy.index.name = None

df_educacao_copy = (df_educacao_copy.mean(axis=1).dropna().to_frame('percentual superior completo (%)'))

display(df_educacao_copy)

                     percentual superior completo (%)
Rondônia                                       11.000
Acre                                           10.975
Amazonas                                       11.150
Roraima                                        13.325
Pará                                            9.125
Amapá                                          15.525
Tocantins                                      13.375
Maranhão                                        8.000
Piauí                                          11.075
Ceará                                           9.550
Rio Grande do Norte                            11.250
Paraíba                                         9.925
Pernambuco                                     10.300
Alagoas                                         9.125
Sergipe                                        10.125
Bahia                                           8.525
Minas Gerais                                   13.225
Espírito Santo                                 14.300
Rio de Janeiro                                 18.800
São Paulo                                      18.950
Paraná                                         15.325
Santa Catarina                                 15.700
Rio Grande do Sul                              14.600
Mato Grosso do Sul                             16.300
Mato Grosso                                    13.450
Goiás                                          14.350
Distrito Federal                               28.325

<class 'pandas.DataFrame'>
Index: 27 entries, Rondônia to Distrito Federal
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   percentual superior completo (%)  27 non-null     float64
dtypes: float64(1)
memory usage: 432.0+ bytes